version: '3.7'

services:
  web:
    build:
      context: ./SuperShop-v02
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/ubuntu/SuperShop-v02/static
      - media_volume:/home/ubuntu/SuperShop-v02/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/ubuntu/SuperShop-v02/static
      - media_volume:/home/ubuntu/SuperShop-v02/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
