FROM python:3.8-slim as base

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

COPY /requirements/_base.txt /requirements/production.txt ./
RUN apt-get update -y \
    && apt-get install -y \
    gcc python3-dev musl-dev tk-dev \ 
    tcl-dev libffi-dev libcairo2-dev \
    && pip install --no-cache-dir -r production.txt 

# Now multistage builds
FROM python:3.8-slim

# create directory for the abraham_linc user
RUN mkdir -p /home/abraham_linc

# create abraham_linc user
RUN addgroup --system abraham_linc && adduser --system abraham_linc --ingroup abraham_linc

# create the appropriate directories
ENV HOME=/home/abraham_linc
ENV APP_HOME=/home/abraham_linc/web_app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

RUN apt-get update -y \
    && apt-get install -y libcairo2-dev
#    && apt-get install -y libpq tk-dev \ 
#    tcl-dev libffi-dev

COPY --from=base /usr/local/lib/python3.8/site-packages/ /usr/local/lib/python3.8/site-packages/
COPY --from=base /usr/local/bin/ /usr/local/bin/

ENV PYTHONPATH /home/abraham_linc/web_app:$PYTHONPATH

# copy entrypoint-prod.sh
# COPY ./entrypoints/entrypoint.prod.sh $APP_HOME

# copy project
COPY . $APP_HOME

# chown all the files to the abraham_linc user
RUN chown -R abraham_linc:abraham_linc $APP_HOME

# change to the abraham_linc user
USER abraham_linc

ENTRYPOINT ["/home/abraham_linc/web_app/entrypoints/entrypoint.prod.sh"]
