###########
# BUILDER #
###########

# pull official base image
FROM python:3.8.3-alpine as compile-image

# set work directory
WORKDIR /app

RUN apk update \
    && pip install --upgrade pip \
    && apk add postgresql-dev gcc python3-dev musl-dev cairo cairo-tools \ 
    jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev \ 
    tcl-dev libffi-dev cairo-dev pango-dev gdk-pixbuf \
    && python -m venv env

ENV PATH="/app/env/bin:$PATH"

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt .
RUN pip install -r requirements.txt

#########
# FINAL #
#########

# pull official base image
FROM python:3.8.3-alpine

# create directory for the ubuntu user
RUN mkdir -p /home/ubuntu

# create the ubuntu user
RUN addgroup -S ubuntu && adduser -S ubuntu -G ubuntu

# create the appropriate directories
ENV HOME=/home/ubuntu
ENV APP_HOME=/home/ubuntu/SuperShop-v02
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# copy entrypoint-prod.sh
COPY ./entrypoint.prod.sh $APP_HOME

# copy project
COPY . $APP_HOME

COPY --from=compile-image /app/env /home/ubuntu/SuperShop-v02/env

# chown all the files to the ubuntu user
RUN chown -R ubuntu:ubuntu $APP_HOME

# change to the ubuntu user
USER ubuntu

ENV PATH="/home/ubuntu/SuperShop-v02/env/bin:$PATH"

# run entrypoint.prod.sh
ENTRYPOINT ["/home/ubuntu/SuperShop-v02/entrypoint.prod.sh"]
